

%fileName = ['/media/richard/camcan/Projects/SpeechTBT/freesurfer/MR1106/probtrackx_commands.txt']; 
%labeltxt = ['/media/richard/camcan/Projects/SpeechTBT/freesurfer/MR1106/rois/rois.txt'];  
%subDir=['/media/richard/camcan/Projects/SpeechTBT/freesurfer/MR1106']; 
fileName = ['/isilon/scratch/rlk41/SpeechTBT/freesurfer/MR1106/probtrackx_commands.txt']; 
labeltxt = ['/isilon/scratch/rlk41/SpeechTBT/freesurfer/MR1106/rois/rois.txt'];  
subDir=['/isilon/scratch/rlk41/SpeechTBT/freesurfer/MR1106']; 

roisDir=[subDir, '/rois']; 

fileID = fopen(fileName, 'w'); 
seedFile = dataread('file', labeltxt, '%s', 'delimiter','\n'); 


% make sure "-x ... " points to a .nii.gz
% make sure "--targetmasks ..." points to targets.txt


for i = 1:length(seedFile)

[filepath, name, ext] = fileparts(seedFile{i}); 
    
c = ['probtrackx2',...
' -x ', seedFile{i},...
' -V 1',...
' -l',...
' --onewaycondition',...
' --omatrix1',...
' -c 0.2',...
' -S 2000',...
' --steplength=0.5',...
' -P 5000',...
' --fibthresh=0.01',...
' --distthresh=0.0',...
' --sampvox=0.0',...
' --forcedir',...
' --opd',...
' -s ', subDir, '/diffusion.bedpostX/merged',...
' -m ', subDir, '/diffusion.bedpostX/nodif_brain_mask',...
' --dir=', subDir, '/results/', name,...
' --targetmasks=', subDir, '/rois/targets.txt',...
' --os2t',...
' --s2tastext',...
' --savepaths',...
%' --waypoints=', subDir, '/rois/waypoints.txt',...
];  

   fprintf(fileID, [c, '\n']);

   commands{i} = c; 
        
end 
fclose(fileID); 

% c = ['probtrackx2',...
% ' -x ', roisDir, '/', seedFile{i},...
% ' -V 1',...
% ' -l',...
% ' --onewaycondition',...
% ' --omatrix1',...
% ' -c 0.2',...
% ' -S 2000',...
% ' --steplength=0.5',...
% ' -P 5000',...
% ' --fibthresh=0.01',...
% ' --distthresh=0.0',...
% ' --sampvox=0.0',...
% '--xfm=',subDir,'diffusion.bedpostX/xfms/seed2nodif_brain.mat'
% ' --forcedir',...
% ' --opd',...
% ' -s ', subDir, 'diffusion.bedpostX/merged',...
% ' -m ', subDir, 'diffusion.bedpostX/nodif_brain_mask',...
% ' --dir=', subDir, '/results/', strrep(seedFile{i},'.nii.gz','')...
% ' --targetmasks=', labeltxt,...
% ' --os2t',...
% ' --s2tastext']; 
