fileName = [subsDir '/' subID '/' 'probtrackx_commands.txt'];
labeltxt = [subsDir '/' subID '/' 'rois.txt'];
subDir   = [subsDir '/' subID];
roisDir  = [subDir '/' 'rois'];

disp(fileName); 
disp(labeltxt); 
disp(subDir); 
disp(roisDir); 

fileID = fopen(fileName, 'w'); 
seedFile = dataread('file', labeltxt, '%s', 'delimiter','\n'); 
for i = 1:length(seedFile)
[filepath, name, ext] = fileparts(seedFile{i}); 
  
c = ['probtrackx2',...
' -x ', seedFile{i},...
' -V 1',...
' -l',...
' --onewaycondition',...
' --omatrix1',...
' -c 0.2',...
' -S 2000',...
' --steplength=0.5',...
' -P 5000',...
' --fibthresh=0.01',...
' --distthresh=0.0',...
' --sampvox=0.0',...
' --forcedir',...
' -s ', subDir, '/diffusion.bedpostX/merged',...
' -m ', subDir, '/diffusion.bedpostX/nodif_brain_mask',...
' --dir=', subDir, '/results/', name,...
' --targetmasks=', subDir, '/targets.txt',...
' --opd',...
' --savepaths',...
' --s2tastext',...
' --os2t'];  

   fprintf(fileID, [c, '\n']);

   commands{i} = c; 
        
end 
fclose(fileID); 

disp('exit matlab'); 
exit

%
%
%' --verbose=2'
%' --save_paths',...
%' --waypoints=', subDir, '/rois/waypoints.txt',...
%' --savepaths',..
